name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: 'macos-latest'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install shellspec
        run: brew tap 'shellspec/shellspec' && brew install 'shellspec'
      - name: Tests
        run: sudo --user='runner' make test  
  coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install kcov
        run: sudo apt-get update && sudo apt-get install -y 'kcov'
      - name: Install homebrew
        run: NONINTERACTIVE=1 bash -c "$(command curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh')"
      - name: Add homebrew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH && echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
      - name: Install shellspec
        run: brew tap 'shellspec/shellspec' && brew install 'shellspec'
      - name: Tests & Coverage
        run: sudo --user='runner' --preserve-env='PATH' bash -c 'make coverage'
      - name: Codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage.json,coverage/cobertura.xml
          flags: unittests
          name: bashembler
          fail_ci_if_error: false
          verbose: false # optional (default = false)
